sudo: required

language: php

services:
  - docker

before_install:
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${TRAVIS_REPO_SLUG}:${APP_VERSION}
  - export STACK_PHP_IMAGE_LATEST=${TRAVIS_REPO_SLUG}:latest
  - cp app.env-dist app.env
  - cd tests
  - cp .env-dist .env
  - make all

script:
  - make run-tests
