sudo: required

language: php

services:
  - docker

before_install:
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${TRAVIS_REPO_SLUG}:${APP_VERSION}
  - export STACK_PHP_IMAGE_LATEST=${TRAVIS_REPO_SLUG}:latest
  - cd tests
  - cp .env-dist .env
  - docker-compose build --pull
  - docker-compose up -d

script:
  - docker-compose run --rm php codecept run cli,unit,functional,e2e
