# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '3.2'
services:
  php:
    build:
      context: .
      # FLAVOUR can be undefinied OR -debian
      # undefined == alpine base image
      # -debian   == debian base image
      dockerfile: Dockerfile${FLAVOUR}
    ports:
      - 80
    depends_on:
      - db
      - redis
    environment:
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      # For composer usage in container
      - GITHUB_API_TOKEN
      - YII_ENV=dev
      - YII_DEBUG=1
      - APP_MAILER_USE_FILE_TRANSPORT=1
      - APP_ADMIN_PASSWORD=admin1
      - APP_ADMIN_EMAIL=admin@local.develop
    volumes:
      # Re-use local composer cache via host-volume
      - type: bind
        source: $HOME/.composer-docker/cache
        target: /root/.composer/cache
        consistency: delegated
      - type: bind
        source: ./composer.json
        target: /app/composer.json
        consistency: cached
      - type: bind
        source: ./composer.lock
        target: /app/composer.lock
        consistency: cached
      - type: bind
        source: ./src
        target: /app/src
        consistency: cached
      - type: bind
        source: ./vendor
        target: /app/vendor
        consistency: delegated
      - type: bind
        source: ./_host-volumes/runtime/mysql
        target: /app/runtime/mysql
        consistency: delegated

  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
