# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 29680:80
    depends_on:
      - db
      - mailcatcher
      - redis
    environment:
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      - PHP_USER_ID=1000
      # For composer usage in container
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer/cache:/root/.composer/cache
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock

  worker:
    build: .
    depends_on:
      - db
      - redis

  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
  mailcatcher:
    image: nisenabe/mailcatcher
    ports:
      - '1080'